version: "3.7"
services:
  app:
    build:
      args:
        user: web
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: soketi-ui
    working_dir: /var/www/
    environment:
    - APP_DEBUG=true
    - APP_KEY=
    - DB_CONNECTION=mysql
    - DB_HOST=127.0.0.1
    - DB_USERNAME=root
    - DB_PASSWORD=
    - DB_DATABASE=soketi-ui
    ports:
      - 8000:80
