version: "3.7"
services:
    app:
        build:
            args:
                user: web
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: soketi-ui
        working_dir: /var/www/
        environment:
            - APP_DEBUG=${APP_DEBUG}
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_PORT=${DB_PORT}
            - DB_HOST=${DB_HOST}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DATABASE=${DB_DATABASE}
        ports:
            - 8000:80
